# Generated by Django 5.1.1 on 2024-12-03 06:40

import case.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagerecord',
            old_name='Message',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='message',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_tickets', to=settings.AUTH_USER_MODEL, validators=[case.models.validate_admin_user], verbose_name='ادمین'),
        ),
        migrations.AlterField(
            model_name='message',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expert_tickets', to=settings.AUTH_USER_MODEL, validators=[case.models.validate_expert_user], verbose_name='کارشناس'),
        ),
        migrations.AlterField(
            model_name='messagerecord',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='پاک شده'),
        ),
    ]
