# Generated by Django 5.1.1 on 2024-12-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_rename_message_messagerecord_message_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('NEW', 'جدید'), ('INPROGRESS', 'باز'), ('CLOSED', 'بسته شده')], default='NEW', max_length=20, verbose_name='حالت'),
        ),
    ]
