from django.urls import path, include
from .views import (AdminHeadRelativeListCreateView, AdminCompanySubjectListCreateView,
                    AdminCasePartnerListCreateView, AdminCaseServiceListCreateView,
                    AdminCasePartnerRetrieveUpdateDestroyView, AdminCompanySubjectRetrieveUpdateDestroyView,
                    CaseRelativesView, AdminCaseCancelView, CaseLogRetrieveUpdateView,
                    ExpertCaseDetail, ExpertCaseList, AdminCaseServiceRetrieveUpdateDestroyView,
                    AdminHeadRelativeRetrieveUpdateDestroyView, AdminCaseListCreateView,
                    AdminCaseRetrieveUpdateDestroyView, CasePartnersView, CaseServiceView,
                    CompanySubjectView, HomePageCaseLogRetrieveView, AdminCasePersonListCreateView,
                    AdminCasePersonRetrieveUpdateDestroyView, CasePersonView)
expert_case_routes = [
    path('case-list', ExpertCaseList.as_view(), name='ExpertCaseList'),
    path('case-detail/<int:pk>', ExpertCaseDetail.as_view(), name='ExpertCaseList')
]
urlpatterns = [
    path('', AdminCaseListCreateView.as_view(), name='AdminCaseListCreateView'),
    path('<int:pk>', AdminCaseRetrieveUpdateDestroyView.as_view(),
         name='AdminCaseRetrieveUpdateDestroyView'),
    path('headrelative/', AdminHeadRelativeListCreateView.as_view(), name='AdminHeadRelativeCreateView'),
    path('headrelative/<int:pk>', AdminHeadRelativeRetrieveUpdateDestroyView.as_view(),
         name='AdminHeadRelativeRetrieveUpdateDestroyView'),
    path('casepartner/', AdminCasePartnerListCreateView.as_view(), name='AdminCasePartnerCreateView'),
    path('casepartner/<int:pk>', AdminCasePartnerRetrieveUpdateDestroyView.as_view(),
         name='AdminCasePartnerRetrieveUpdateDestroyView'),
    path('caseservice/', AdminCaseServiceListCreateView.as_view(),
         name='AdminCaseServiceListCreateView'),
    path('caseservice/<int:pk>', AdminCaseServiceRetrieveUpdateDestroyView.as_view(),
         name='AdminCaseServiceRetrieveUpdateDestroyView'),
    path('companysubject/', AdminCompanySubjectListCreateView.as_view(), name='AdminCompanySubjectListCreateView'),
    path('companysubject/<int:pk>', AdminCompanySubjectRetrieveUpdateDestroyView.as_view(),
         name='AdminCompanySubjectRetrieveUpdateDestroyView'),
    path('caseperson', AdminCasePersonListCreateView.as_view(), name='AdminCasePersonListCreateView'),
    path('caseperson/<int:pk>', AdminCasePersonRetrieveUpdateDestroyView.as_view(),
         name='AdminCasePersonRetrieveUpdateDestroyView'),
    path('homepage-caselog/<int:pk>', HomePageCaseLogRetrieveView.as_view(), name='HomePageCaseLogRetrieveView'),
    path('caselog/<int:pk>', CaseLogRetrieveUpdateView.as_view(), name='CaseLogCreateView'),
    path('expert/', include(expert_case_routes)),
    path('cancel/<int:pk>', AdminCaseCancelView.as_view(), name='AdminCaseCancelView'),
    path('<int:pk>/headrelative/', CaseRelativesView.as_view(), name='CaseRelativesView'),
    path('<int:pk>/casepartner/', CasePartnersView.as_view(), name='CasePartnersView'),
    path('<int:pk>/caseservice/', CaseServiceView.as_view(), name='CaseServiceView'),
    path('<int:pk>/companysubject/', CompanySubjectView.as_view(), name='CompanySubjectView'),
    path('<int:pk>/caseperson/', CasePersonView.as_view(), name='CasePersonView'),
]
