# Generated by Django 5.1.1 on 2024-12-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_options_alter_user_birthday_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[('MALE', 'مرد'), ('FEMALE', 'زن'), ('OTHER', 'دیگر')], default='OTHER', verbose_name='جنسیت'),
        ),
    ]
