# Generated by Django 5.1.1 on 2024-10-20 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='step_name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('order', models.IntegerField(blank=True, null=True, unique=True, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head_first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='head_first_name')),
                ('head_last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='head_last_name')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='job_title')),
                ('iran_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='iran_phone_number')),
                ('oman_phone_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='oman_phone_number')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='address')),
                ('email', models.EmailField(blank=True, max_length=255, null=True, verbose_name='email')),
                ('bank_card_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='bank_card_number')),
                ('passport', models.FileField(blank=True, null=True, upload_to='temp', verbose_name='passport')),
                ('passport_description', models.TextField(blank=True, null=True, verbose_name='passport_description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='temp', verbose_name='image')),
                ('image_description', models.TextField(blank=True, null=True, verbose_name='image_description')),
                ('first_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='first_person')),
                ('second_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='second_person')),
                ('third_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='third_person')),
                ('fourth_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='fourth_person')),
                ('fifth_person', models.CharField(blank=True, max_length=255, null=True, verbose_name='fifth_person')),
                ('status', models.CharField(choices=[('ONGOING', 'ONGOING'), ('FINISHED', 'FINISHED'), ('FAILED', 'FAILED')], default='ONGOING', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('expert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CasePartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last_name')),
                ('percent', models.IntegerField(blank=True, null=True, verbose_name='percent')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(blank=True, max_length=255, null=True, verbose_name='service')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseSubStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('substep_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='substep_name')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='description')),
                ('status', models.CharField(choices=[('NEW', 'NEW'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='NEW', max_length=20, verbose_name='status')),
                ('order', models.IntegerField(blank=True, null=True, unique=True, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substeps', to='case.casestep')),
            ],
        ),
        migrations.CreateModel(
            name='CaseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='case.case')),
                ('substep', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='case.casesubstep')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='substep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='case.casesubstep'),
        ),
        migrations.CreateModel(
            name='CompanySubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=255, null=True, verbose_name='subject')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_subjects', to='case.case')),
            ],
        ),
        migrations.CreateModel(
            name='HeadRelative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='first_name')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='last_name')),
                ('relation', models.CharField(blank=True, max_length=255, null=True, verbose_name='relation')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated_at')),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='case.case')),
            ],
        ),
    ]
