# Generated by Django 5.1.1 on 2024-10-22 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='status',
            new_name='case_status',
        ),
        migrations.RemoveField(
            model_name='casesubstep',
            name='status',
        ),
        migrations.AddField(
            model_name='case',
            name='substep_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='NEW', max_length=20, verbose_name='status'),
        ),
    ]
