# Generated by Django 5.1.1 on 2024-10-23 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0004_remove_case_substep_status_caselog_substep_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='substep',
        ),
    ]
