# Generated by Django 5.1.1 on 2024-10-26 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0005_remove_case_substep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caselog',
            name='substep_status',
        ),
        migrations.AddField(
            model_name='caselog',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date'),
        ),
        migrations.AddField(
            model_name='caselog',
            name='next_substep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_logs', to='case.casesubstep'),
        ),
        migrations.AddField(
            model_name='casesubstep',
            name='doer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='doer'),
        ),
        migrations.AddField(
            model_name='casesubstep',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
