# Generated by Django 5.1.1 on 2024-10-26 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0006_remove_caselog_substep_status_caselog_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesubstep',
            name='order',
        ),
        migrations.AddField(
            model_name='caselog',
            name='substep_status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('DONE', 'DONE'), ('INPROGRESS', 'INPROGRESS'), ('FAILED', 'FAILED')], default='NEW', max_length=20, verbose_name='substep_status'),
        ),
        migrations.AddField(
            model_name='casesubstep',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previouss', to='case.casesubstep'),
        ),
        migrations.AddField(
            model_name='casesubstep',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nextt', to='case.casesubstep'),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='doer',
            field=models.CharField(blank=True, choices=[('EXPERT', 'EXPERT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='doer'),
        ),
    ]
