# Generated by Django 5.1.1 on 2024-10-26 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0007_remove_casesubstep_order_caselog_substep_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesubstep',
            name='previous',
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='case.casesubstep'),
        ),
    ]
