# Generated by Django 5.1.1 on 2024-10-26 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0008_remove_casesubstep_previous_alter_casesubstep_next'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casesubstep',
            name='next',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='case.casesubstep'),
        ),
    ]
