# Generated by Django 5.1.1 on 2024-10-26 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0010_alter_casesubstep_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesubstep',
            name='previous_id',
            field=models.IntegerField(blank=True, null=True, verbose_name='previous_id'),
        ),
    ]
