# Generated by Django 5.1.1 on 2024-10-26 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0011_casesubstep_previous_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesubstep',
            name='previous_id',
        ),
        migrations.AddField(
            model_name='casesubstep',
            name='previous',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_substep', to='case.casesubstep', unique=True),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_substep', to='case.casesubstep', unique=True),
        ),
    ]
