# Generated by Django 5.1.1 on 2024-10-26 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0012_remove_casesubstep_previous_id_casesubstep_previous_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caselog',
            name='next_substep',
        ),
    ]
