# Generated by Django 5.1.1 on 2024-10-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0013_remove_caselog_next_substep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesubstep',
            name='previous',
        ),
    ]
