# Generated by Django 5.1.1 on 2024-10-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0015_alter_casesubstep_next'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casesubstep',
            name='is_active',
        ),
        migrations.AddField(
            model_name='casesubstep',
            name='is_start',
            field=models.BooleanField(blank=True, null=True, unique=True, verbose_name='is_start'),
        ),
    ]
