# Generated by Django 5.1.1 on 2024-10-29 05:42

import case.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0017_alter_casesubstep_is_start'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_cases', to=settings.AUTH_USER_MODEL, validators=[case.models.validate_admin_user]),
        ),
        migrations.AddField(
            model_name='caselog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='temp', verbose_name='file'),
        ),
        migrations.AlterField(
            model_name='case',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
