# Generated by Django 5.1.1 on 2024-10-29 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0018_case_admin_caselog_file_alter_case_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_logs', to='case.case'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='substep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substep_logs', to='case.casesubstep'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='substep_status',
            field=models.CharField(choices=[('INPROGRESS', 'INPROGRESS'), ('DONE', 'DONE'), ('FAILED', 'FAILED')], default='INPROGRESS', max_length=20, verbose_name='substep_status'),
        ),
    ]
