# Generated by Django 5.1.1 on 2024-10-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0019_alter_caselog_case_alter_caselog_substep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesubstep',
            name='type',
            field=models.CharField(blank=True, choices=[('TEXT', 'TEXT'), ('FILE', 'FILE')], max_length=255, null=True, verbose_name='type'),
        ),
    ]
