# Generated by Django 5.1.1 on 2024-11-09 09:41

import case.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0020_casesubstep_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'verbose_name': 'پرونده', 'verbose_name_plural': 'پرونده ها'},
        ),
        migrations.AlterModelOptions(
            name='caselog',
            options={'verbose_name': 'لاگ', 'verbose_name_plural': 'لاگ ها'},
        ),
        migrations.AlterModelOptions(
            name='casepartner',
            options={'verbose_name': 'شریک', 'verbose_name_plural': 'شرکا'},
        ),
        migrations.AlterModelOptions(
            name='caseservice',
            options={'verbose_name': 'خدمات', 'verbose_name_plural': 'خدمات'},
        ),
        migrations.AlterModelOptions(
            name='casestep',
            options={'verbose_name': 'مرحله پرونده', 'verbose_name_plural': 'مراحل پرونده'},
        ),
        migrations.AlterModelOptions(
            name='casesubstep',
            options={'verbose_name': 'زیرمرحله پرونده', 'verbose_name_plural': 'زیرمراحل پرونده'},
        ),
        migrations.AlterModelOptions(
            name='companysubject',
            options={'verbose_name': 'موضوع شرکت', 'verbose_name_plural': 'موضوعات شرکت'},
        ),
        migrations.AlterModelOptions(
            name='headrelative',
            options={'verbose_name': 'خویشاوند', 'verbose_name_plural': 'خویشاوندان'},
        ),
        migrations.AlterField(
            model_name='case',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='case',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_cases', to=settings.AUTH_USER_MODEL, validators=[case.models.validate_admin_user], verbose_name='ادمین'),
        ),
        migrations.AlterField(
            model_name='case',
            name='bank_card_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره کارت بانکی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('ONGOING', 'ONGOING'), ('FINISHED', 'FINISHED'), ('CANCELED', 'CANCELED')], default='ONGOING', max_length=20, verbose_name='وضعیت پرونده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='case',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expert_cases', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس'),
        ),
        migrations.AlterField(
            model_name='case',
            name='fifth_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شخص پنجم پرونده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='first_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شخص اول پرونده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='fourth_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شخص چهارم پرونده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='head_first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='case',
            name='head_last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='temp', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='case',
            name='image_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات عکس'),
        ),
        migrations.AlterField(
            model_name='case',
            name='iran_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تلفن ایران'),
        ),
        migrations.AlterField(
            model_name='case',
            name='job_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان شغلی'),
        ),
        migrations.AlterField(
            model_name='case',
            name='oman_phone_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تلفن عمان'),
        ),
        migrations.AlterField(
            model_name='case',
            name='passport',
            field=models.FileField(blank=True, null=True, upload_to='temp', verbose_name='پاسپورت'),
        ),
        migrations.AlterField(
            model_name='case',
            name='passport_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات پاسپورت'),
        ),
        migrations.AlterField(
            model_name='case',
            name='second_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شخص دوم پرونده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='third_person',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شخص سوم پرونده'),
        ),
        migrations.AlterField(
            model_name='case',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='case_logs', to='case.case', verbose_name='پرونده'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='temp', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='substep',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='substep_logs', to='case.casesubstep', verbose_name='زیرمرحله'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='substep_status',
            field=models.CharField(choices=[('INPROGRESS', 'INPROGRESS'), ('DONE', 'DONE'), ('FAILED', 'FAILED'), ('CANCELED', 'CANCELED')], default='INPROGRESS', max_length=20, verbose_name='وضعیت زیرمرحله'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casepartner',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partners', to='case.case', verbose_name='پرونده'),
        ),
        migrations.AlterField(
            model_name='casepartner',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='casepartner',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='casepartner',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='casepartner',
            name='percent',
            field=models.IntegerField(blank=True, null=True, verbose_name='درصد سهم'),
        ),
        migrations.AlterField(
            model_name='casepartner',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='caseservice',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='case.case', verbose_name='پرونده'),
        ),
        migrations.AlterField(
            model_name='caseservice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='caseservice',
            name='service',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='خدمات'),
        ),
        migrations.AlterField(
            model_name='caseservice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casestep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='casestep',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='casestep',
            name='order',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ترتیب'),
        ),
        migrations.AlterField(
            model_name='casestep',
            name='step_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام مرحله'),
        ),
        migrations.AlterField(
            model_name='casestep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='doer',
            field=models.CharField(blank=True, choices=[('EXPERT', 'EXPERT'), ('ADMIN', 'ADMIN')], max_length=255, null=True, verbose_name='انجام دهنده'),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='is_start',
            field=models.BooleanField(default=False, verbose_name='شروع'),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='next',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous', to='case.casesubstep', unique=True, verbose_name='زیر مرحله بعدی'),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='step',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='substeps', to='case.casestep', verbose_name='مرحله'),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='substep_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام زیرمرحله'),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='type',
            field=models.CharField(blank=True, choices=[('TEXT', 'TEXT'), ('FILE', 'FILE')], max_length=255, null=True, verbose_name='نوع'),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companysubject',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_subjects', to='case.case', verbose_name='پرونده'),
        ),
        migrations.AlterField(
            model_name='companysubject',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='companysubject',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع'),
        ),
        migrations.AlterField(
            model_name='companysubject',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='headrelative',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relatives', to='case.case', verbose_name='پرونده'),
        ),
        migrations.AlterField(
            model_name='headrelative',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='headrelative',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='headrelative',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='headrelative',
            name='relation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نسبت'),
        ),
        migrations.AlterField(
            model_name='headrelative',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
