# Generated by Django 5.1.1 on 2024-11-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0021_alter_case_options_alter_caselog_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='head_first_name',
            field=models.CharField(default='default name', max_length=255, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='case',
            name='head_last_name',
            field=models.CharField(default='default lastname', max_length=255, verbose_name='نام خانوادگی'),
        ),
    ]
