# Generated by Django 5.1.1 on 2024-11-27 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0022_alter_case_head_first_name_alter_case_head_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselog',
            name='date',
            field=models.DateTimeField(blank=True, default='2024-11-27 12:15:41', null=True, verbose_name='تاریخ'),
        ),
    ]
