# Generated by Django 5.1.1 on 2024-11-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0023_alter_caselog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselog',
            name='date',
            field=models.DateTimeField(blank=True, default='2024-11-27 13:45:13', null=True, verbose_name='تاریخ'),
        ),
    ]
