# Generated by Django 5.1.1 on 2024-11-30 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0024_alter_caselog_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caselog',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='تاریخ'),
        ),
    ]
