# Generated by Django 5.1.1 on 2024-12-01 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0025_alter_caselog_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='fifth_person',
        ),
        migrations.RemoveField(
            model_name='case',
            name='first_person',
        ),
        migrations.RemoveField(
            model_name='case',
            name='fourth_person',
        ),
        migrations.RemoveField(
            model_name='case',
            name='second_person',
        ),
        migrations.RemoveField(
            model_name='case',
            name='third_person',
        ),
        migrations.CreateModel(
            name='CasePerson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(blank=True, null=True, unique=True, verbose_name='ترتیب')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='case.case', verbose_name='پرونده')),
            ],
            options={
                'verbose_name': 'فرد پشنهادی',
                'verbose_name_plural': 'افراد پشنهادی',
            },
        ),
    ]
