# Generated by Django 5.1.1 on 2024-12-03 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0026_remove_case_fifth_person_remove_case_first_person_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_status',
            field=models.CharField(choices=[('ONGOING', 'در حال انجام'), ('FINISHED', 'اتمام یافته'), ('CANCELED', 'لغو شده')], default='ONGOING', max_length=20, verbose_name='وضعیت پرونده'),
        ),
        migrations.AlterField(
            model_name='caselog',
            name='substep_status',
            field=models.CharField(choices=[('INPROGRESS', 'در حال انجام'), ('DONE', 'انجام شده'), ('FAILED', 'ناموفق'), ('CANCELED', 'لغو شده')], default='INPROGRESS', max_length=20, verbose_name='وضعیت زیرمرحله'),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='doer',
            field=models.CharField(blank=True, choices=[('EXPERT', 'کارشناس'), ('ADMIN', 'ادمین')], max_length=255, null=True, verbose_name='انجام دهنده'),
        ),
        migrations.AlterField(
            model_name='casesubstep',
            name='type',
            field=models.CharField(blank=True, choices=[('TEXT', 'متن'), ('FILE', 'فایل')], max_length=255, null=True, verbose_name='نوع'),
        ),
    ]
