# Generated by Django 5.1.1 on 2024-12-03 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0027_alter_case_case_status_alter_caselog_substep_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='casesubstep',
            name='substep_hour_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='زمان زیرمرحله'),
        ),
        migrations.AlterField(
            model_name='casepartner',
            name='percent',
            field=models.FloatField(blank=True, null=True, verbose_name='درصد سهم'),
        ),
        migrations.AlterField(
            model_name='caseperson',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='ترتیب'),
        ),
    ]
