# Generated by Django 5.1.1 on 2025-02-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case', '0029_alter_casepartner_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='birth_year',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='سال تولد'),
        ),
        migrations.AddField(
            model_name='case',
            name='home_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نشانی منزل'),
        ),
        migrations.AddField(
            model_name='case',
            name='national_id',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='case',
            name='work_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نشانی محل کار'),
        ),
    ]
